wercker: master branch check for prod

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -43,6 +43,15 @@ build:
 deploy:
     steps:
       - script:
+          name: Check if branch is master
+          code: |
+            if [ "$RZP_WERCKER_CURR_PIPELINE_ID" == "$RZP_WERCKER_PROD_PIPELINE_ID" ]; then
+              if [ "$WERCKER_GIT_BRANCH" != "master" ]; then
+                echo "[ERROR] Cannot deploy a non-master branch to prod"
+                exit $?
+              fi
+            fi
+      - script:
           name: List directory
           code: ls -lah
       - script:
